apiVersion: apps/v1
kind: Deployment
metadata:
  name: odds-shopweb
  namespace: odds-shop
spec:
  selector:
    matchLabels:
      app: odds-shopweb
  template:
    metadata:
      labels: 
         app: odds-shopweb
    spec:
     containers:
     -  name: odds-shopweb
        image: ghcr.io/bazsup/odds-shopweb:v1