apiVersion: apps/v1
kind: Deployment
metadata:
  name: odds-shopgw
  namespace: odds-shop
spec:
  selector:
    matchLabels:
      app: odds-shopgw
  template:
    metadata:
      labels: 
         app: odds-shopgw
    spec:
     containers:
     -  name: odds-shopgw
        image: ghcr.io/bazsup/odds-shopgw:v2