apiVersion: apps/v1
kind: Deployment
metadata:
  name: odds-shopapi
  namespace: odds-shop
spec:
  selector:
    matchLabels:
      app: odds-shopapi
  template:
    metadata:
      labels: 
         app: odds-shopapi
    spec:
     containers:
     -  name: odds-shopapi
        image: ghcr.io/bazsup/odds-shopapi:v1