apiVersion: v1
kind: Service
metadata:
  name: odds-shopapi
  namespace: odds-shop
spec:
  selector:
      app: odds-shopapi
  ports:
    - name: odds-api-http
      port: 8080
      targetPort: 8080
      protocol: TCP
    